services:
  http-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: http-proxy-rs
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/proxy/https://httpbin.org/status/200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 128M
    #       cpus: '0.25'
    # 
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
